#ifndef GLOBAL_HPP
#define GLOBAL_HPP

#pragma once
#define PHASE_INITIAL_IMAGE 1
#define PHASE_HOME_PAGE 2
#define PHASE_STAGE_1 3

#define BLUE_NORMAL_OBJECT 1
#define BROWN_NORMAL_OBJECT 2
#define GREEN_NORMAL_OBJECT 3
#define PINK_NORMAL_OBJECT 4
#define ORANGE_NORMAL_OBJECT 5
#define WHITE_NORMAL_OBJECT 6
#define YELLOW_NORMAL_OBJECT 7

#define BLUE_STRIPE_OBJECT 101
#define BROWN_STRIPE_OBJECT 102
#define GREEN_STRIPE_OBJECT 103
#define PINK_STRIPE_OBJECT 104
#define ORANGE_STRIPE_OBJECT 105
#define WHITE_STRIPE_OBJECT 106
#define YELLOW_STRIPE_OBJECT 107

#define BLUE_FLOWER_OBJECT 201
#define BROWN_FLOWER_OBJECT 202
#define GREEN_FLOWER_OBJECT 203
#define PINK_FLOWER_OBJECT 204
#define ORANGE_FLOWER_OBJECT 205
#define WHITE_FLOWER_OBJECT 206
#define YELLOW_FLOWER_OBJECT 207

#define BLUE_STARFLOWER_OBJECT 201
#define BROWN_STARFLOWER_OBJECT 202
#define GREEN_STARFLOWER_OBJECT 203
#define PINK_STARFLOWER_OBJECT 204
#define ORANGE_STARFLOWER_OBJECT 205
#define WHITE_STARFLOWER_OBJECT 206
#define YELLOW_STARFLOWER_OBJECT 207

#define BLUE_TRIANGLEFLOWER_OBJECT 301
#define BROWN_TRIANGLEFLOWER_OBJECT 302
#define GREEN_TRIANGLEFLOWER_OBJECT 303
#define PINK_TRIANGLEFLOWER_OBJECT 304
#define ORANGE_TRIANGLEFLOWER_OBJECT 305
#define WHITE_TRIANGLEFLOWER_OBJECT 306
#define YELLOW_TRIANGLEFLOWER_OBJECT 307

#define RAINBOWBALL_OBJECT 301


#include <glm/vec2.hpp> 
#include <stack>
#include <memory>
#include "ObjectInformation.hpp"

extern glm::vec2 stage1_position[38];
extern int stage1_neibor[38][6];
extern Objectinformation stage1[38];
extern int is_click;
extern int stage_point_goal[13];
extern int stage_point_counter[13];

void InitializeStage1();

#endif // GLOBAL_HPP
