#ifndef GLOBAL_HPP
#define GLOBAL_HPP
#pragma once

#define PHASE_INITIAL_IMAGE 0
#define PHASE_HOME_PAGE 1

#define BLUE_NORMAL_OBJECT 0
#define BROWN_NORMAL_OBJECT 1
#define GREEN_NORMAL_OBJECT 2
#define PINK_NORMAL_OBJECT 3
#define ORANGE_NORMAL_OBJECT 4
#define WHITE_NORMAL_OBJECT 5
#define YELLOW_NORMAL_OBJECT 6




#endif // GLOBAL_HPP
